// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkhFB04rCuM7i0TbAblHt6ELF8_u8r07Y',
    appId: '1:680513862900:web:84b3b8fbb9976e2296b2a1',
    messagingSenderId: '680513862900',
    projectId: 'cookbox-f0caa',
    authDomain: 'cookbox-f0caa.firebaseapp.com',
    storageBucket: 'cookbox-f0caa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkhFB04rCuM7i0TbAblHt6ELF8_u8r07Y',
    appId: '1:680513862900:android:2da8d47faa62a2f196b2a1',
    messagingSenderId: '680513862900',
    projectId: 'cookbox-f0caa',
    storageBucket: 'cookbox-f0caa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkhFB04rCuM7i0TbAblHt6ELF8_u8r07Y',
    appId: '1:680513862900:ios:f3aab5b9bda1124d96b2a1',
    messagingSenderId: '680513862900',
    projectId: 'cookbox-f0caa',
    storageBucket: 'cookbox-f0caa.appspot.com',
    iosBundleId: 'com.cookbox.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkhFB04rCuM7i0TbAblHt6ELF8_u8r07Y',
    appId: '1:680513862900:ios:f3aab5b9bda1124d96b2a1',
    messagingSenderId: '680513862900',
    projectId: 'cookbox-f0caa',
    storageBucket: 'cookbox-f0caa.appspot.com',
    iosBundleId: 'com.cookbox.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkhFB04rCuM7i0TbAblHt6ELF8_u8r07Y',
    appId: '1:680513862900:web:fbb3784e60c009eb96b2a1',
    messagingSenderId: '680513862900',
    projectId: 'cookbox-f0caa',
    authDomain: 'cookbox-f0caa.firebaseapp.com',
    storageBucket: 'cookbox-f0caa.appspot.com',
  );
}
